### PR TITLE
New proposed logo

### PR DESCRIPTION
**Pull request by ska-ibees**
New proposed logo added. 
README.md updated

### CODE REVIEW

**Comment by ska-ibees** [comment]
@JuanDCG Here you go...

**Comment by JuanDCG** [comment]
I like a lot the new logo.

But could you please edit it with a semi-dark-green color in text color and in white space.

I like it white a lot but would like see the same concept design with a green color.

**Comment by ska-ibees** [comment]
Terraodoo2
Terraodoo

**Comment by JuanDCG** [comment]
Sorry, probably is my bad english.

I refer to the space between circle and hexagon, if could be green. And also the color of text.

So, change white in the first design to green

**Comment by JuanDCG** [comment]
And I see that you change my bad grammar and English expressions.

I'm agree with your changes.

So, it should be perfect it also modified introduction.rst with the same text you put at Readme.md

And I have a gap, because I have the same text on website but with markdown, so you can fork website repository and PR to that.

Thanks a lot

**Comment by ska-ibees** [comment]
Terraodoo3

Terraodoo

Here you go.

**Comment by ska-ibees** [comment]
Terraodoo4
Terraodoo

This one is without drop shadow.

**Comment by ska-ibees** [comment]
I think it looks more elegant without green.

**Comment by ska-ibees** [comment]
> And I have a gap, because I have the same text on website but with markdown, so you can fork website repository and PR to that.

Done in new [PR ](https://github.com/TerradooCloud/website/pull/2)

**Comment by JuanDCG** [comment]
@ska-ibees 

Please add another PR for the text for the documentation repository

**Comment by JuanDCG** [comment]
Thank you a lot @ska-ibees

**Pull request closed without merging**
